### ISSUE TITLE
Add public getters/setters for protected properties

### ISSUE THREAD

**Issue by hkdobrev** [erusev/parsedown#155]
Recent commits introduced a bunch of protected methods and properties.

However if I want to just modify the `blockMarkers` property I need to create a new class extending `Parsedown`. I'd prefer to just have a public setter like `setBlockMarkers()` which would allow me to set the markers to a specific array for an instance of the `Parsedown` class.

I think properties which should have a public getter and a public setter are:
- `blockMarkers`
- `definitionMarkers`
- `unmarkedBlockTypes`
- `spanMarkers`
- `spanMarkerList`
- `textLevelElements`

Example usage:

``` php
$parsedown = new Parsedown;

$parsedown->setBlockMarkers(array(
    '§' => array('myCustomParagraphmarker')
));

$html = $parsedown->parse($markdown);
```

**Comment by aidantwoods** [comment]
@hkdobrev I don't think we could allow access to setting of markers – since blocks and inlines sometimes re-specify these markers after being called as part of their specific parsing algorithm (so custom markers likely won't work in many cases because even though the block/inline method will be called, it won't always behave as if a known marker had been used).
