### ISSUE TITLE
Nested ordered lists do not support more than 2 levels of indentation

### ISSUE THREAD

**Issue by zipang** [erusev/parsedown#270]
Try these nested lists in the parser :

1. Type some Markdown text
  1. Insert some nested ordered list
    1. We should be 1.1.1 (level 3) here
    2. Why oh my?
  2. One level back (1.2) here
    1. We should be 1.2.1 (level 3) here
2. Hit _Parse_
3. See the flat lists that result

Apparently, github isn't using `parsedown` because the indentation it produces in this issue is correct...? :)

**Comment by erusev** [comment]
It does support more levels, but it expects more indentation. It shouldn't. I'll see what I can do.

**Comment by zipang** [comment]
Yes ! That's what i noticed shortly after !
If i try to indent using 4 spaces, it produce the desired indentation !

**Comment by aidantwoods** [comment]
Could you give the original text from the comment within a code block (add ` ``` ` above and below the text) so we can see the original indentation?

**Comment by aidantwoods** [comment]
I'm going to close this one because I'm not really sure what the intended result is – if the problem was similar to https://github.com/erusev/parsedown/issues/581 then this will be fixed in the next release. If there is still an issue feel free to reopen though :)

Our indentation rules for list should line up with CommonMark now.

**Comment by JHubi1** [comment]
So, hi there. This issue seems old, but I believe it's the exact problem I have.
When I try to enter something like this:
```
- a
  - b
    - c
```
<details>
<summary>Which should lead to this</summary>

- a
  - b
    - c
</details>

Even in the [demo page](https://parsedown.org/demo) (so not an issue on my side), this is returned:
```
<ul>
<li>a
<ul>
<li>b</li>
<li>c</li>
</ul></li>
</ul>
```
Which then displays it like this:
- a
  - b
  - c

I'm not sure if there's a solution to that, but I couldn't find it. I'd be happy if someone could help me

**Comment by taufik-nurrohman** [comment]
Either wait for version 2.0.0 to be released or use [my Markdown parser](https://github.com/taufik-nurrohman/markdown) instead, which is not yet stable (unfortunately):

![List Spec.](https://github.com/erusev/parsedown/assets/1669261/566f99c3-90d6-4bc7-ada5-f6fe0bd86480)

**Comment by JHubi1** [comment]
Thank you, updating to `v2.0.0-beta-1` did the trick for me
