### ISSUE TITLE
Markdown inside HTML!

### ISSUE THREAD

**Issue by josephernest** [erusev/parsedown#319]
I'd like to have 2 columns with Markdown inside. Unfortunately, Markdown is not parsed if it is inside a html `<td>` :

    <table><tr><td>This is some **Markdown** content.</td>
    <td>##Features
    * Feature 1
    * Feature 2
    * Feature 3</td></tr></table>

I also tried with things like :

  | header1 | header2 |
  | ----------  | ---------- |

but impossible to have easily have two columns with long lists, etc.

[Here](http://stackoverflow.com/a/13538239/1422096) seems to be a nice way to do it:

    <div markdown="1">
    *markdown*
    </div>

Any idea?

**Comment by erusev** [comment]
Have a look at Parsedown Extra.

**Comment by josephernest** [comment]
Thanks @erusev . Do you have a small example of how you would do it, with Extra?
Would you use `<table>` anyway or `| ----- | ----- |` things?

**Comment by bgbrandongomez** [comment]
I know this issue is closed, but I wanted to point out that Parsedown Extra does not work with my Markdown.

Below is my tested code for the parser. It works in PHP Markdown Extra, but not Parsedown Extra. I don't really need this as I just use a Javascript parser to parse this in combination with Jekyll, but I am sure somebody else does.

## Visualization
<div style="text-align:center; float:left; border:5px solid transparent" markdown="1">

![Missing Image Caption][image]
</div>

[image]: /images/image1.png
