### ISSUE TITLE
Is there an option not replace \t to 4 space?

### ISSUE THREAD

**Issue by doiftrue** [erusev/parsedown#363]
Is it danger if don't do the replace? Why it is important and how can I disable this option.

I examine the `Parsedown.php` file and not found any possibility do this, except comment following lines in private `lines` method:

```
            if (strpos($line, "\t") !== false)
            {
                $parts = explode("\t", $line);

                $line = $parts[0];

                unset($parts[0]);

                foreach ($parts as $part)
                {
                    $shortage = 4 - mb_strlen($line, 'utf-8') % 4;

                    $line .= str_repeat(' ', $shortage);
                    $line .= $part;
                }
            }
````

Please help do this correctly.

**Comment by erusev** [comment]
it'd work but it won't consider text indented with tabs as a code block and nested list items as nested

**Comment by doiftrue** [comment]
Thanks!

if that makes sense, it would be perfect if in next version it can be done without changing the original `Parsdown.php` file.

Maybe take out this part of code in single protected method. Or add corresponding setting for class.

**Comment by doiftrue** [comment]
now I noticed that parser broke such `\t` too:

<pre>
	// it's one tab, not spaces
</pre>

`\t` becomes 4 space, because of code I mentioned before. It's maybe good when parsedown parse code itself in ~~~*~~~ or any else. But here I have `pre` tag, why parser need to touch code inside the tag?

I thought parser don't touch code inside html tag at all... Except I would do it myself.

All this looks like bug.

**Comment by erusev** [comment]
This is expected and consistent with the other Markdown parsers.

**Comment by doiftrue** [comment]
Yes, but I need it and maybe I'm not lonely. If it possible, would be perfect to add such option, or give chance to do it without changing private `lines` method. Now I have no choice. `\t` is important for me...

**Comment by erusev** [comment]
I understand, but there are a lot of other things that are higher priority, so I can't promise.

**Comment by doiftrue** [comment]
Anyway thanks!

**Comment by doiftrue** [comment]
In the end I solved the problem (replace 4 space on tabs) in another way. After all parsedown manipulations have been occured, I filter resulting text with such code (it's fast anought):

```
$text = preg_replace_callback('/^[ ]{4,}/m', function( $m ){
	return preg_replace('/[ ]{4}/', "\t", $m[0] );
}, $text ); 
```

*P.S. maybe better close this thread*

**Comment by Nerdmind** [comment]
Hello. I would also find it good if tabulators remain tabluators. Especially for the indentation of code one has actually only to use tabulators (everything else is semantically wrong and inflexible). What would happen if I defined in CSS that a tab should be displayed in the HTML pre-tags like 12 spaces (`tab-size: 12;`)? This does not work because the CSS does not find any tabulators, but only four hard blanks. If the user places a tab anywhere within its text or source code, the tab should always remain a tab. Especially within HTML pre-tags where I may post my source code which is semantically correct indent with tabs! If the markdown parser replaces my tabs, the code isn't anymore THE code I've inserted.

**If this is my original code which I want to put into my markdown (tab indentation) …**
```
class Foobar {
	protected $propertyA = 1;
	protected $propertyB = 1;
}
```

**… Parsedown will make this, which is not my code anymore:**
```
class Foobar {
    protected $propertyA = 1;
    protected $propertyB = 1;
}
```

If you compare the two code examples, you'll see that GitHub also retains the tab indentation in the first example and uses a width like 8 spaces for displaying them (8 is the default width in HTML pre-tags for tabs). And this is EXACT the same code I entered in the issue editor. The second example is not my code because tabs were replaced by spaces. This is inflexible if someone would copy the code into his IDE in which he uses, for example, a width like 15 spaces for displaying tabs.

**Shortly:** Tabulators should remain tabulators. :)
