### ISSUE TITLE
Table rendering in parsedown

### ISSUE THREAD

**Issue by AjubaNet** [erusev/parsedown#379]
Following table render nicely in PHP MarkdownExtra that I use from Michael F.. However, with Parsedown, this produces table that is missing empty cells. While this behavior can be justified in tbody row 1, it cannot be justifed in row 3 and row 4, where table cell(s) shifted to the left, hence losing column alignment. Please consider addressing this.

```
a|b|c
-|-|-
d|e| 
f|g|h
|a|c
|a|
```

Above markdown code is also expected to work the same, even with extra leading pipes.
Ideally, I would like a completely balanced table, with all rows have same number of columns.

**Comment by aidantwoods** [comment]
I think that Parsedown maybe shouldn't be missing the cells, but the column alignment seems to match what GitHub gives:

GitHub
![screen shot 2018-02-28 at 17 14 27](https://user-images.githubusercontent.com/3288888/36801768-dddcbcb4-1caa-11e8-943d-db12ce1524b7.png)
Parsedown
![screen shot 2018-02-28 at 17 15 30](https://user-images.githubusercontent.com/3288888/36801822-0263d176-1cab-11e8-98ce-aa5a9985ebfc.png)

**Comment by aidantwoods** [comment]
Closing since the result matches spec

**Comment by AjubaNet** [comment]
In the last two rows, leading '|' should've rendered first cell as blank.

IMHO, Consideration comes from the reference, which is header row.

If header row has leading pipe character, all rows are expected to have leading pipe. However, rows without leading pipe are rendered assuming '|' in the beginning.

On the contrary, if header row does NOT have leading pipe character, any rows that have leading pipe character should render first cell as blank.

**Comment by aidantwoods** [comment]
The reason that the leading pipe is before first row is because the spec says that leading and trailing pipes are optional (but doesn't distinguish cases where some rows have this and others do not).

> [...] A leading and trailing pipe is also recommended for clarity of reading, and if there’s otherwise parsing ambiguity.

https://github.github.com/gfm/#tables-extension-

You could try opening an issue over at https://github.com/github/cmark/issues to discuss a spec change. GitHub will also be able to get some metrics on whether changes would break too many existing texts (for example if we include a leading pipe in the header, and then require one in subsequent rows this would cause a subset of valid tables to no longer render).

**Comment by AjubaNet** [comment]
I agree on the github markdown specs part.


However, I use markdown extra parser by Michel Fortin, which practices the
behavior I requested.
https://michelf.ca/projects/php-markdown/extra/#table

In addtion, online editors like the following, demonstrate same behavior.:

https://pandao.github.io/editor.md/en.html

This could be a variable controlled behavior. For users like me with
thousands of markdown
pages, this is a deal breaker. This use case is not explicitly documented
and I am slowly
moving away from it.
