### ISSUE TITLE
when to parse markdown file no style, how to add css file

### ISSUE THREAD

**Issue by jasonhzy** [erusev/parsedown#400]

**Comment by kminchev** [comment]
You can use HTML elements.

**Comment by devmath** [comment]
You write in markdown, and stylish in CSS. On the main-page, in head, link CSS and create styles for HTML elements, normally. In the end, PHP just converts Markdown to HTML

**Comment by master-caster** [comment]
I know you don't want to have styling code in markdown but sometimes it would be useful
if you can set the attribute _class_ or _id_ or something else for some parts of the markdown code so 
you can style it more specific instead of setting styles for all table tags.

I'm using phpdoc for Documentation. It is very useful for documenting a REST API to
use the markdown style for tables. But all themes for the documentation come with
CSS defining styles for tables and more.

I have opened an issue there before
https://github.com/phpDocumentor/phpDocumentor2/issues/1825

but since i worked around this behaviour by editing
parsedown you might be interested in it too.
