### ISSUE TITLE
Can't create extension using special characters

### ISSUE THREAD

**Issue by zelpa** [erusev/parsedown#401]
I've been trying to get this code to work, but it seems that I can't use the '>>' marker because blockQuote already uses '>'. Is there any way to fix this? Or will I have to use a different character?

```
function __construct()
{
    $this->InlineTypes['>>'] []= 'QuoteThing';

    $this->inlineMarkerList .= '>>';
}

protected function inlineQuoteThing($Excerpt)
{
    if (preg_match('/^(>>)([0-9]+)/m', $Excerpt['text'], $matches))
    {

        $postid = $matches[2];

        return array(
            'extent' => strlen($matches[0]),
            'element' => array(
                'name' => 'a',
                'text' => $matches[0],
                'attributes' => array(
                    'href' => '#' . $postid,
                ),
            ),
        );
    }
}
```

**Comment by erusev** [comment]
Put `QuoteThing` so that it's before `Quote` in the `InlineTypes` array.

**Comment by tovic** [comment]
https://github.com/erusev/parsedown-extra/blob/cbd74e2e1fc8985f5bcafc5066bfa960caa60800/ParsedownExtra.php#L35

**Comment by Zelpa** [comment]
So just doing `array_unshift($this->InlineTypes['>'], 'QuoteThing');` in __construct should be enough? Because that doesn't seem to work either. Even if I manually edit parsedown.php and remove anything relating to quotes from it the code still doesn't work. Am I missing something obvious here? It works if I use any character other than >.

**Comment by erusev** [comment]
Markers can contain only one character and `>>` is two and `$this->inlineMarkerList .= '>>';` is unnecessary because the `>` is already in the string.

**Comment by tovic** [comment]
In the source code, you will se that `blockRule`, `blockList` and `inlineEmphasis` have the same character prefix &rarr; `*`. I think the most important here is to set the `handler` to `line` because [`lines`](https://github.com/erusev/parsedown/blob/490a8f35a4163f59230f53c34f1fbb22a864c01e/Parsedown.php#L114&L279) is for block elements and [`line`](https://github.com/erusev/parsedown/blob/490a8f35a4163f59230f53c34f1fbb22a864c01e/Parsedown.php#L986&L1054) is for inline elements.

Try something like this (untested):

~~~ .php
function __construct()
{
    // put before `SpecialCharacter`
    array_unshift($this->InlineTypes['>'], 'QuoteThing');
}

protected function inlineQuoteThing($Excerpt)
{
    if (preg_match('/^>>(\d+)/', $Excerpt['text'], $matches))
    {

        $postid = $matches[2];

        return array(
            'extent' => strlen($matches[0]),
            'element' => array(
                'name' => 'a',
                'handler' => 'line', // ← this
                'text' => $matches[0],
                'attributes' => array(
                    'href' => '#' . $postid,
                ),
            ),
        );
    }
}
~~~

**Comment by Zelpa** [comment]
adding `'handler' => 'line',` somehow made my server return a 502, that's a first. That doesn't seem to work either sadly, even after I tried switching some stuff around.

**Comment by erusev** [comment]
Hm, now I realized that you're adding an inline type - `blockQuote` should not interfere with your type because `blockQuote` is a block type, also:

> and `$this->inlineMarkerList .= '>>';` is unnecessary because the `>` is already in the string

I thought you're talking about a block type when I wrote that - you'll probably need to do something like `$this->inlineMarkerList .= '>';`

**Comment by Zelpa** [comment]
Seems that `>` already exists in inlineMarkerList, so adding it doesn't help. One thing I did notice however is that for some reason HTML Purifier was interfering with normal quotes, which seems pretty odd. I was running HTML Purifier on the text and THEN Parsedown, so I have no clue why it was doing anything. Doesn't seem to help though, nothing I try fixes my problem.

**Comment by Zelpa** [comment]
Now that I think about it HTML Purifier could possibly be converting > to &gt; which Parsedown might not understand.

**Comment by aidantwoods** [comment]
Please reopen if you're still having this issue – as far as I know `>` should be be fine to use as a marker :)
