### ISSUE TITLE
Allow to remove the englobing paragraph

### ISSUE THREAD

**Issue by Hypoaristerolactotherapist** [erusev/parsedown#43]
I would like to remove the `<p></p>` englobing the html output as it has not specifically been asked.

Just make an optional parameter to remove it in parse

``` php
$parser = new Parsedown();
$output = $parser->parse($input,false);//Without <p></p>
$output = $parser->parse($input,true);//With <p></p>
$output = $parser->parse($input);//With <p></p>
```

Thanks

**Comment by EminezArtus** [comment]
Sorry to resurrect this again...

echo Parsedown::instance()->line('Hello _Parsedown_!');

Is a terrible idea because your assuming that its one item your parsing. This fails with lists..
I don't understand why you guys went in the most complicated route to just remove the paragraph wrapper. 

My suggestion is just add a true or false option to remove the wrapper.
