### ISSUE TITLE
Extra empty lines not showing up in preview using parsedown and codeigniter

### ISSUE THREAD

**Issue by wolfgang1983** [erusev/parsedown#450]
Previewing parsedown not displaying correct newlines in preview

![demo](https://cloud.githubusercontent.com/assets/5113934/20636234/14701c90-b3ce-11e6-8e39-6b07b2a1b92a.png)

With ```<br/>``` manually entered texarea I do not want to have to enter ```<br/>``` all the time if need to have extra lines

![demo1](https://cloud.githubusercontent.com/assets/5113934/20637776/817db5c2-b3f6-11e6-975e-5d5ee58a128f.PNG)

Question: How can I get it to show correct lines amount of lines that are in the textarea to preview?

Controller How I load the parsedown.php

if I replace `\n` with `<br>` it will effect the code indents I have tried nl2br() also

```
<?php

class Example extends CI_Controller {

	public function __construct() {
		parent::__construct();
                // application > libraries > Parsedown.php
		$this->load->library('parsedown'); 
	}

	public function index()
	{
		$this->load->view('example_view');
	}

	public function preview() {
		$data['success'] = false;
		$data['output'] = '';

		if ($this->input->post('html')) {
			
			$string = str_replace('\n', '\r\n', $this->input->post('html'));
			
			$data['success'] = true;
			$data['output'] = $this->parsedown->text($string);
			
		}

		echo json_encode($data);
	}
}
```

Script

```

<script type="text/javascript">
$( document ).ready(function() {
	$('#editor').on('paste cut mouseup mousedown mouseout keydown keyup', function(){
		var postData = {
			'html' : $('#editor').val(),
		};
		$.ajax({
			type: "POST",
			url: "<?php echo base_url('example/preview');?>",
			data: postData,
			dataType: 'json',
			success: function(json){
				$('#output').html(json['output']);
			}
		});
	});
});
</script>
```

it's one of the best  markdowns this is the only thing I can that need to fix.

**Comment by aidantwoods** [comment]
Just to clarify a little, is this the bug? (i.e. Parsedown stripping line breaks *inside* a code block)

<img width="1088" alt="screen shot 2016-11-25 at 14 15 35" src="https://cloud.githubusercontent.com/assets/3288888/20627764/18190b04-b31a-11e6-855f-2f25e3bd1c57.png">


With this being the expected output? 
<img width="1390" alt="screen shot 2016-11-25 at 14 15 39" src="https://cloud.githubusercontent.com/assets/3288888/20627771/20ac305c-b31a-11e6-8a8b-be3dd4b96cf2.png">

**Comment by wolfgang1983** [comment]
Yes. The second  image is correct but also not using code format.

**Comment by PhrozenByte** [comment]
He's not talking about code blocks @aidantwoods, he wants something similar to `nl2br()` :wink: But we should fix this CommonMark incompatibility :smile:

@wolfgang1983: Markdown works with paragraphs, not with line breaks. You'll have to explicitly tell Parsedown to create a "empty" paragraph. There are many ways to accomplish this, here are some examples:
```markdown
paragraph 1

<br />

paragraph 2
```
```markdown
paragraph 1

&nbsp;

paragraph 2
```

The following is the most syntactically correct, but depending on your website's stylesheet it may not be visible:
```markdown
paragraph 1

<p></p>

paragraph 2
```

**Comment by wolfgang1983** [comment]
@PhrozenByte I tried using nl2br but when it does it effect the code indent.

**Comment by PhrozenByte** [comment]
You are not supposed to use `nl2br()` 😆 This was just to explain @aidantwoods what you're trying to achieve :wink:

**Comment by aidantwoods** [comment]
Issue https://github.com/erusev/parsedown/issues/448#issuecomment-259654137 may help RE inserting lines within normal text, if you really can't use HTML to do it. 

Also, for the literal '—' character inside `` ` `` you'll need to use the actual character. But if just in regular text, Parsedown should cope fine with that HTML entity encoding you're using (I.e. It will work if not within backticks)

**Comment by aidantwoods** [comment]
cc @erusev shall I make a PR with something similar to the diff linked to in the above comment? (similar: can probably implement a bit cleaner).  I guess this is a feature that a few people would find useful (even though it will break a few commonmark tests if enabled).

**Comment by erusev** [comment]
Parsedown has an option called `setBreaksEnabled`, wouldn't that resolve the issue?

**Comment by aidantwoods** [comment]
@erusev I think it's about regular text (though I guess the code blocks is a separate issue). I think `setBreaksEnabled` only copes with adding a single line break (as far as I can tell with testing). The diff should honour them all. (is this a bug in `setBreaksEnabled`?)

**Comment by wolfgang1983** [comment]
Have updated question/issue with image

**Comment by PhrozenByte** [comment]
As said, this is expected behavior, it's consistent to both the original Markdown description and the CommonMark specs. @wolfgang1983, you'll either have to extend Parsedown (see [wiki](https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions)) or use one of the workarounds described in https://github.com/erusev/parsedown/issues/450#issuecomment-263023847.

**Comment by erusev** [comment]
With `setBreaksEnabled` set to true, new lines should get converted to `<br>` and if I understand correctly, this is what the issue is about.

**Comment by PhrozenByte** [comment]
@erusev: I always thought that `setBreaksEnabled(true)` is about following GitHub's line break principles. So

```markdown
This is a longer text with
a custom line break
```

gets

---

This is a longer text with
a custom line break

---

Normally Parsedown (and most other Markdown parsers; this btw complies to both the original Markdown description and the CommonMark specs) would parse this to (i.e. no line break)

---

This is a longer text with a custom line break

---

This doesn't affect multiple empty lines, those are still parsed as paragraphs. So

```markdown
This is a longer text with



three empty lines
```

gets

---

This is a longer text with



three empty lines

---

with both GitHub flawored Markdown and Parsedown, no matter `setBreaksEnabled()` is set to `true` or not. This is IMO the expected behavior, as it matches GitHub flavored markdown and other Markdown parsers with similar behavior to `setBreaksEnabled(true)`.

@wolfgang1983 in contrast is trying to achieve something like this with the previous example:

---

This is a longer text with

&#8203;

three empty lines

---

**Comment by erusev** [comment]
@PhrozenByte 

Right, I believe you are correct, it won't work to resolve this issue.

**Comment by aidantwoods** [comment]
@erusev is it worth adding in another built in setter for literal line breaks (similar (but possibly cleaner than) this patch I threw together https://github.com/erusev/parsedown/issues/448#issuecomment-259654137)? Given this issue (and the one opened in the linked comment) are both requesting the same functionality I'd guess it might be a useful addon for at least a few people.

Also, since `lines` handler is really the gating function here (responsible for losing the excess line breaks before `setBreaksEnabled` can see them), I can't really see this being an easy thing to write an extension for (without just overwriting the entire `lines` function with almost identical functionality). Having extensions completely replace that core function is probably quite likely to break things across updates too IMO.

**Comment by PhrozenByte** [comment]
@aidantwoods: Just my 2 cents: Sure, why not (with another option like your suggested `setLiteralBreaks()`), however I personally don't like this `nl2br()`-like behavior... This produces semantically incorrect results. The example Markdown

```markdown
paragraph 1



paragraph 2
```

should result in the HTML

```html
<p>paragraph 1</p>
<p></p>
<p>paragraph 2</p>
```

when this new option `setLiteralBreaks()` is set to `true`.

**Comment by wolfgang1983** [comment]
@aidantwoods on my code a where would place it I did a test tun but nothing happened.

**Comment by erusev** [comment]
@aidantwoods This seems like a feature that should rather be built is an extension, I appreciate the offer, though.

**Comment by aidantwoods** [comment]
@erusev Alright, no worries 👍 

@wolfgang1983 I've created a seperate branch with `setLiteralBreaks` added in there – so just grab Parsedown.php out of there to apply the patch, and use `->setLiteralBreaks(true)` to enable it.

Branch: https://github.com/aidantwoods/parsedown/tree/patch-6

Diff: https://github.com/aidantwoods/parsedown/commit/fd681ee683a1e17f0e2afd75909d7dabf453a1b7#diff-ed0d3da57330712681e64f838087ea47

**Comment by wolfgang1983** [comment]
@aidantwoods  will give it ago. I like this parsedown.php my fav so far.

**Comment by wolfgang1983** [comment]
@aidantwoods works fine now thanks

**Comment by wolfgang1983** [comment]
@aidantwoods  I have just started testing it when I get code from database and I get a error using jquery preview was OK. But i have to get it from DB now.

```

A PHP Error was encountered

Severity: Notice

Message: Uninitialized string offset: 0

Filename: libraries/Parsedown.php

Line Number: 636

Backtrace:

File: C:\xampp\htdocs\myproject\application\libraries\Parsedown.php
Line: 636
Function: _error_handler

File: C:\xampp\htdocs\myproject\application\libraries\Parsedown.php
Line: 177
Function: blockQuoteContinue

File: C:\xampp\htdocs\myproject\application\libraries\Parsedown.php
Line: 39
Function: lines

File: C:\xampp\htdocs\myproject\application\modules\catalog\controllers\qna\Thread.php
Line: 94
Function: text

File: C:\xampp\htdocs\myproject\application\modules\catalog\controllers\qna\Thread.php
Line: 53
Function: get_form

File: C:\xampp\htdocs\myproject\index.php
Line: 315
Function: require_once

```

**Comment by aidantwoods** [comment]
@wolfgang1983 Have you got some test data you could give me some test data that replicates the issue so I can track it down?

**Comment by wolfgang1983** [comment]
@aidantwoods  I use [codeigniter](https://www.codeigniter.com/) I have put the parsedown.php in my libraries folder here is my controller I have loaded the library in the __construct are and on the get_form is where I use ->text() http://pastebin.com/raw/HaQ3eBR9

**Comment by aidantwoods** [comment]
@wolfgang1983 have you got any of the actual text that caused the error?

(i.e. something that would be returned by `$post_tmp_info['message']` – which is given to `$Parsedown->text()` in your code)

**Comment by wolfgang1983** [comment]
@aidantwoods  I tried it just like this way it does not seem to like it when add empty lines in. I just put `"\n"` as a new line for testing.

```

$text = '';
$text .= '> Hello';
$text .= "\n";
$text .= "\n";
$text .= '<pre>';
$text .= '<p></p>';
$text .= '</pre>';

$Parsedown = new Parsedown();
$Parsedown->setLiteralBreaks(true); 
```

And throws same error.

```

A PHP Error was encountered

Severity: Notice

Message: Uninitialized string offset: 0

Filename: libraries/Parsedown.php

Line Number: 636

Backtrace:

File: C:\xampp\htdocs\myproject\application\libraries\Parsedown.php
Line: 636
Function: _error_handler

File: C:\xampp\htdocs\myproject\application\libraries\Parsedown.php
Line: 177
Function: blockQuoteContinue

File: C:\xampp\htdocs\myproject\application\libraries\Parsedown.php
Line: 39
Function: lines

File: C:\xampp\htdocs\myproject\application\modules\catalog\controllers\qna\Newthread.php
Line: 27
Function: text

File: C:\xampp\htdocs\myproject\index.php
Line: 315
Function: require_once
```

 echo $Parsedown->text($text);

**Comment by aidantwoods** [comment]
@wolfgang1983 Just updated the branch (diff: https://github.com/aidantwoods/parsedown/commit/539f152bab5e34551263bc8585f80d93e3ba08a9)

Moved the code that creates text on a blank line to before the continuable/completable checks are made (which rely on the first char in the line).


By the way, because setLiteralBreaks essentially just removes the ability for a blank line to interrupt a paragraph – you won't be able to start an unmarked code block (i.e. from your example `'    <div></div>'`) without further modification. Using a fenced block will work though.

**Comment by wolfgang1983** [comment]
@aidantwoods Hi again, I know this is closed but there is a small bug for some reason it effects the code indent when enabled $Parsedown->setLiteralBreaks(true);

**Comment by aidantwoods** [comment]
Is this happening with the markerless code block? (I.e. Text that is indented >= 4 times to become code?)

**Comment by wolfgang1983** [comment]
@aidantwoods when I have my code intended 4 spaces and have  setLiteralBreaks(true) in preview as showing in image for some reason removes pre and code tags. What I would of liked is only when I click enter on a line does it add newline only for that line i use $Parsedown->text()

**Comment by aidantwoods** [comment]
Yeah, that's expected behaviour really – as said in https://github.com/erusev/parsedown/issues/450#issuecomment-267959893.

You'd need to use ` ``` `, or ` ~~~ ` to start and end a ***marked*** code block. 

Per commonmark spec: an *unmarked* code block cannot interrupt a paragraph (but a line containing only whitespace can).  (An unmarked code block is one that is indented, and contains no (non-whitespace) '*markers*' to delimit the code).

`->setLiteralBreaks(true)` ***prevents*** a new line interrupting a paragraph (so no newlines can interrupt the paragraph before your *unmarked* code block starts – so it cannot start).

You can use a *marked* code block to enclose code, the only other solution would be to have `->setBreaksEnabled` enable some logic that allows an *unmarked* code block to interrupt a paragraph (possibly based on some criteria – like the last line was blank).

**Comment by wolfgang1983** [comment]
Thanks ones again

**Comment by wolfgang1983** [comment]
Hi, @aidantwoods I have noticed a small issue with the code you gave me with lists the if press enter after the last list number or bulleted one it should clear it but for some reason when ever I start a new line after the last list item it still thinks its in list. How to solve this

**Comment by aidantwoods** [comment]
Seems this is an issue with Parsedown (rather than this particular extension).

`setLiteralBreaks(true)` will prevent a (blank) line from interrupting a block structure. So the extension will cause Parsedown to see something like

~~~markdown
1. list item
2. list item


```
code
```
~~~

as 

~~~markdown
1. list item
2. list item
```
code
```
~~~

Parsedown parses the former (correctly) as 

```html
<ol>
<li>list item</li>
<li>list item</li>
</ol>
<pre><code>code</code></pre>
```

But fails when parsing the latter by neglecting to honour list content indentation rules specified in commonmark, and so the following is produced for the latter:

```html
<ol>
<li>list item</li>
<li>list item
<pre><code>code</code></pre></li>
</ol>
```

The correct result for a commonmark compliant parser for the latter markdown text can be found here: http://spec.commonmark.org/dingus/?text=1.%20list%20item%0A2.%20list%20item%0A%60%60%60%0Acode%0A%60%60%60

and is as follows:
```html
<ol>
<li>list item</li>
<li>list item</li>
</ol>
<pre><code>code
</code></pre>
```

Probably the best thing to do is open another issue with Parsedown about code blocks not being able to interrupt a list block based on indentation. Once Parsedown can do this then you'll be able to start a new code block after a list with `setLiteralBreaks` enabled.
