### ISSUE TITLE
preg_match in inlineLink() causes segfault

### ISSUE THREAD

**Issue by gene-sis** [erusev/parsedown#458]
the preg_match pattern
``/^[(]((?:[^ ()]|[(][^ )]+[)])+)(?:[ ]+("[^"]*"|\'[^\']*\'))?[)]/``
causes a segfault on a huge link or an attempt to insert a base64-image

The parts in the alternation group are mutually exclusive, so it should be no problem to an additonal quantifier (+ or ++) for first alternative and a possessive quantifier for the group.
``/^[(]((?:[^ ()]++|[(][^ )]+[)])++)(?:[ ]+("[^"]*"|\'[^\']*\'))?[)]/``

**Comment by erusev** [comment]
That's interesting, I was not familiar with possessive quantifiers, how would the new regex affect the general case - is it possible that it'd make it slower? Thanks.

**Comment by aidantwoods** [comment]
@erusev The suggested change should actually do the contrary (speed the general case up).

As mentioned, because the alternatives are mutually exclusive (no possibility for the matches in the alternatives to overlap) then backtracking would offer no advantage here (neither in speed or ability to match). Hence the transition from a greedy to possessive quantifier for the entire group.

It's a bit easier to visualise the speed increase by looking at how the regex engine steps over a string it attempts to match:
The current regex steps over each character
<img width="800" alt="screen shot 2017-01-05 at 16 06 02" src="https://cloud.githubusercontent.com/assets/3288888/21687367/e8a9a09c-d360-11e6-8d42-2f918b167b25.png">
(https://regex101.com/r/m1QeuP/1/debugger)

Whereas the new regex is allowed to match as many characters as it can is a single step
<img width="825" alt="screen shot 2017-01-05 at 16 06 08" src="https://cloud.githubusercontent.com/assets/3288888/21687368/e8aabf68-d360-11e6-89c8-24dd0056464f.png">
(https://regex101.com/r/xhIF4H/1/debugger)

**Comment by erusev** [comment]
Thanks @aidantwoods, @gene-sis, would you like to create a pull request?

**Comment by gene-sis** [comment]
I wasn't familiar with them either.

[Possessive quantifiers](http://www.regular-expressions.info/possessive.html) (or [atomic grouping](http://www.regular-expressions.info/atomic.html)) should speed up all kind of input, as they "eat up" the characters and prevents backtracking.
For this regex there should be only one way to resolve, so backtracking should be not necessary.

The [original regex](https://regex101.com/r/fsyk7O/1) needs 81 steps with an example input.
The [new regex](https://regex101.com/r/DouebK/1) or the [alternative](https://regex101.com/r/nVTAiL/2) will always need 13 steps for a simple link (some more with parentheses within the link)

With the additional quantifier but without the [possessive quantifier for the group](https://regex101.com/r/knAsHe/1), it works for matches but results in catastrophic backtracking if the input doesn't match.


Side note: Using the regex with possessive quantifier would allow the use of base64 images. Some people may not want to allow base64 images (copyright issues, database space).

**Comment by erusev** [comment]
> I could create a PR if you want me to.

That'd be great, thanks and thanks for the explanation.

**Comment by gene-sis** [comment]
@erusev: can I use a base64 version of [this md-image](http://parsedown.org/md.png) for the tests? (it would become part of the repo)

I also have to change the [first regex](https://regex101.com/r/rSttbI/1)
`\[((?:[^][]|(?R))*)\]`
to [use possessive quantifier](https://regex101.com/r/DYK17i/1)
`\[((?:[^][]++|(?R))*+)\]`
for the same reason.

**Comment by erusev** [comment]
@gene-sis 

> can I use a base64 version of this md-image for the tests

Sure, that'd be perfect.

> I also have to change the first regex of inlineLink()

Is this to prevent issues with links where the text of the link is too long?

Thanks.

**Comment by gene-sis** [comment]
> Is this to prevent issues with links where the text of the link is too long?

The initial issue occurred when a user tried sth like
`![MD Logo](data:image/png;base64,... image data ...==)`
Changing the second inlineLink() regex would be enough in that case

Changing the first inlineLink() regex would also cover
`[![MD Logo](data:image/png;base64,... image data ...==) and text](http://example.com)`
