### ISSUE TITLE
Could this regex be changed to pass theme check ?

### ISSUE THREAD

**Issue by danyj** [erusev/parsedown#469]
Our theme is failing WordPress theme check because of this regex 

https://github.com/erusev/parsedown/blob/master/Parsedown.php#L772

theme check dev suggested this change

https://github.com/WordPress/theme-check/issues/64

do you think that change is ok and if yes could you make the change in the class itself?

We can change it but we might forget it on future parsedown updates.

**Comment by aidantwoods** [comment]
The change would be fine in terms of it being functionally the same, though this strikes me as more of a bug in Theme Check than Parsedown? As in, the contents of a string should be able to contain PHP language constructs without being interpreted as a literal language construct.

Looks like that issue was raised almost 2 years ago now, might be worth raising the issue again and seeing if they're more receptive to fixing? (I mention fixing it there, as I'd guess that this going unfixed will likely cause issues other than this particular one).

**Comment by danyj** [comment]
>  strikes me as more of a bug in Theme Check than Parsedow

I agree , Il try again with them but I doubt they will change it since their  check looks for shortcode instances so seems like they would need to more changes, and in parsedown the change is very minor. Will close for now.

**Comment by danyj** [comment]
Asked there lets see what we get. https://github.com/WordPress/theme-check/issues/186
It would be great  if either one of you would make the change.
