### ISSUE TITLE
Unexpected paragraph in unordered list

### ISSUE THREAD

**Issue by ulab** [erusev/parsedown#474]
Using the following Markdown:

```markdown
* abc
* def
* ghi

* jkl
* mno
* pqr

abc
```

I get paragraph tags in the "ghi" list element that I don't think should be there. Interestingly it does not get added to the 2nd list "pqr" if a paragraph follows.

```html
<ul>
<li>abc</li>
<li>def</li>
<li>
<p>ghi</p>
</li>
<li>jkl</li>
<li>mno</li>
<li>pqr</li>
</ul>
<p>abc</p>
```

**Comment by kminchev** [comment]
According to the [Demo], the original parser produces almost identical results.

[Demo]:http://parsedown.org/demo

**Comment by ulab** [comment]
I didn't expect a set of <p> there, but perhaps a 2nd list? With the original parser there's another set of <p> for the next list element. But I'm not sure if that's better?

**Comment by aidantwoods** [comment]
I think this borders more on expected behaviour? The markdown given is conventionally interpreted as a single list, where the third item contains some extra spacing.

The [commonmark reference parser](http://spec.commonmark.org/dingus/) produces `<p>` tags on all lists

```html
<ul>
<li>
<p>abc</p>
</li>
<li>
<p>def</p>
</li>
<li>
<p>ghi</p>
</li>
<li>
<p>jkl</p>
</li>
<li>
<p>mno</p>
</li>
<li>
<p>pqr</p>
</li>
</ul>
<p>abc</p>
```

Taking a look at the [appropriate part of the spec](http://spec.commonmark.org/0.27/#lists)

> A list is loose if any of its constituent list items are separated by blank lines, or if any of its constituent list items directly contain two block-level elements with a blank line between them. Otherwise a list is tight. (The difference in HTML output is that paragraphs in a loose list are wrapped in `<p>` tags, while paragraphs in a tight list are not.)

So it looks like the break between 

```markdown
* ghi

* jkl
```

*should* cause the list to become "loose", and so `<p>` appears in all items.

**Comment by ulab** [comment]
Thanks for providing the link to the commonmark specs. Yes, that's a behaviour I'd expect more than just one element being made paragraph.

(It also showed me what I should do to separate my two lists correctly - by using a different marker.)

**Comment by aidantwoods** [comment]
@ulab #475 addresses these inconsistencies between list items
