### ISSUE TITLE
Feature request: remove the `PHPUnit_Framework_TestCase` class alias

### ISSUE THREAD

**Issue by cedx** [erusev/parsedown#490]
I don't use your project directly : it is used by one of my Composer dependencies (I don't known which one).

I'm using PHPUnit v6 (based on namespaces) for my unit tests. In the [`bootstrap.php`](https://github.com/erusev/parsedown/blob/master/test/bootstrap.php) file, a class alias is created. This alias causes problems with most IDEs: "Multiple definition exist for class TestCase".

This breaks a bit features like code completion, member resolution or inheritance analysis. So, I think you should remove this alias.

**Comment by erusev** [comment]
I'd love to remove it, this would lead to failing builds on Travis CI because the builds for the newer PHP versions use a newer PHPUnit and it uses different class names.

**Comment by hkdobrev** [comment]
@erusev Testing on a specific version of PHPUnit should be done with locking to an older version of PHPUnit which supports the lowest PHP version you want to test against. You can lock it via Composer as a dev dependency and test on Travis CI with `vendor/bin/phpunit`.

@cedx You should have the tests or other development-related artefacts on your dependencies excluded in most cases.

@erusev On that note, you could exclude tests from the normal Packagist.org distribution of Parsedow by adding `test/ export-ignore` to `.gitattributes` which would exclude them from GitHub archives on releases which Composer is using when installing via `dist` (default) instead of `source`.

**Comment by erusev** [comment]
Thanks @hkdobrev 

Anyone willing to create a PR with the changes suggested above?

**Comment by Kishdia** [comment]
@cedx If you use PhpStorm, you can make target file as plain text.
in this case "erusev/parsedown/test/bootstrap.php"
https://blog.jetbrains.com/webide/2011/04/exclude-single-file/

**Comment by cedx** [comment]
@Kishdia Ok, but this is not a good solution. If I had enough free time, I would create the wanted PR as the suggestion from @hkdobrev is clearly the best option...

It is fairly easy:
- PHPUnit as a development dependency in the `composer.json` file (let you choose exactly what versions you want to support or use, independently from the CI environment).
- a Composer script that launch the PHPUnit executable : launching it from Composer allow to skip the `vendor/bin/` prefix as [this folder is added to the system path by Composer](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands).
- a Travis CI configuration file that launch the Composer script.

That's what I've done on most of [my PHP projects](https://github.com/cedx?utf8=%E2%9C%93&tab=repositories&q=&type=&language=php). For example :
- [composer.json](https://github.com/cedx/phpunit-expect/blob/master/composer.json) : see the `scripts` section (the `test` script).
- [.travis.yml](https://github.com/cedx/phpunit-expect/blob/master/.travis.yml): see the `script` section.

**Comment by sebastiaanluca** [comment]
Would be great to get this through. Have been asking myself why code completion suddenly stopped working in a few projects and just found out it's due to Parsedown's class aliasing. Excluding the Parsedown test directory for each project is somewhat annoying tbh, but good enough for now (as long as I remember to do so each time).

**Comment by aidantwoods** [comment]
Fixed in https://github.com/erusev/parsedown/commit/691e36b1f241e7000fa36d176a2b13de4820b64c
