### ISSUE TITLE
Link allows javascript which could lead to XSS issues

### ISSUE THREAD

**Issue by lin714093880** [erusev/parsedown#497]
So I don't know if this is a bug or an expected feature, so please correct me if I'm wrong, but I found that I actually can write javascript links like this:

```
[test](javascript:alert%281%29)
```

An alert does pop out and this behavior is actually disallowed in GitHub. 

People can do nasty things if a victim does click on one of these links.

**Comment by aidantwoods** [comment]
I've proposed some changes to parsedown here to prevent that https://github.com/erusev/parsedown/pull/495, which you can grab a little early from here https://github.com/aidantwoods/parsedown/tree/anti-xss

Just be sure to set
```php
$Parsedown->setMarkupEscaped(true);
```
To disable HTML tags (since the markdown language permits HTML by default). 

Lastly if you're willing to test that version, feedback is welcome/encouraged :).

**Comment by lin714093880** [comment]
@aidantwoods cool, thanks. I think people will want your PR in master, to keep things safer.

I'll grab your version and inform you if I find any issues.

**Comment by sergeysviridenko** [comment]
@erusev what about this problem? Will it solve?
