### ISSUE TITLE
Fails to parse tabs (breaks everything!)

### ISSUE THREAD

**Issue by exezin** [erusev/parsedown#549]
It seems parsedown is failing entirely when I try to parse the following content, causing other html in the same div to render incorrectly as well (perhaps breaking php somewhere?).  This happens even inside a code block.

The issue could be related to indenting?  I'm really not sure here.

````
(do

(window_setMode 800 600)
(graphics_setBackgroundColor 70 40 50 255)

(= pressed_key 0)
(loop (not (event_quit))
	(graphics_clear)
	(keyboard_update)	

	(= pressed_key (keyboard_keypressed))	
	(when (not (eq pressed_key nil))
		(print pressed_key)
		(print " ---- "
		(print (keyboard_keyreleased))
		))
	
	(graphics_swap)
	)

)
````

This is the php that handles this, the issue happens even if I don't actually do anything with $content.

````
$content = $Parsedown->setBreaksEnabled(true)->text($rowitem['post_content']);
$content = $purifier->purify($content);
````

And just to confirm, it is parsedown causing this and removing the parsedown part removes the issue (but obviously removes markdown, lol)

--EDIT--
It looks like tab characters are breaking it.  Seems to be the same as #527 (I used the same workaround as stated in that thread for now as it was causing severe issues)

**Comment by aidantwoods** [comment]
Seems to be okay for me, is this not the result you were expecting?

<img width="822" alt="screen shot 2018-03-28 at 02 46 57" src="https://user-images.githubusercontent.com/3288888/38004036-4dc354b0-3232-11e8-9530-e36fae2cd876.png">

**Comment by exezin** [comment]
It's hard to tell without it being rendered in HTML, but the indenting doesn't look right there?  #527 This issue appears to be the same thing (And the workaround noted in there about finding and replacing tab characters resolved the issue for me as well as others..)

**Comment by aidantwoods** [comment]
Is your issue that tabs are being replaced by spaces?

**Comment by aidantwoods** [comment]
CommonMark gives the same result as far as I can tell? (except that Parsedown replaces tabs with spaces when it shouldn't)

http://spec.commonmark.org/dingus/?text=(do%0A%0A(window_setMode%20800%20600)%0A(graphics_setBackgroundColor%2070%2040%2050%20255)%0A%0A(%3D%20pressed_key%200)%0A(loop%20(not%20(event_quit))%0A%09(graphics_clear)%0A%09(keyboard_update)%09%0A%0A%09(%3D%20pressed_key%20(keyboard_keypressed))%09%0A%09(when%20(not%20(eq%20pressed_key%20nil))%0A%09%09(print%20pressed_key)%0A%09%09(print%20%22%20----%20%22%0A%09%09(print%20(keyboard_keyreleased))%0A%09%09))%0A%09%0A%09(graphics_swap)%0A%09)%0A%0A)

**Comment by aidantwoods** [comment]
> are you sure your editor used to make test.md isn't replacing tab characters with spaces?

I used `vim` with basically no config and checked it didn't replace the tabs :)

**Comment by aidantwoods** [comment]
Just to be sure, you can see that the byte is `09` (tab in ascii hex) where we're expecting there to be tabs (whitespace represented by dots on the right column).

<img width="837" alt="screen shot 2018-03-28 at 13 31 05" src="https://user-images.githubusercontent.com/3288888/38028932-4f6e8762-328c-11e8-9d2a-7dbd32985b84.png">

**Comment by exezin** [comment]
> Is your issue that tabs are being replaced by spaces?

No, multiple-tabs where breaking it entirely, causing parsedown to just cease functioning and it would put out borked html that messed up rendering for a lot of stuff.

Replacing tabs with spaces was the workaround for this issue.

**Comment by aidantwoods** [comment]
Is the issue still happening, if so in which version?

**Comment by exezin** [comment]
The issue still exists but as I said I'm using the replacing tabs with spaces workaround noted in the other thread, I've not updated Parsedown since I started this issue so I can't comment on that.  It's running on php7.0 and Ubuntu (16 & 17)

**Comment by aidantwoods** [comment]
Is the CommonMark result the same as you were experiencing? (i.e. that code blocks are forming)
CommonMark result:
http://spec.commonmark.org/dingus/?text=(do%0A%0A(window_setMode%20800%20600)%0A(graphics_setBackgroundColor%2070%2040%2050%20255)%0A%0A(%3D%20pressed_key%200)%0A(loop%20(not%20(event_quit))%0A%09(graphics_clear)%0A%09(keyboard_update)%09%0A%0A%09(%3D%20pressed_key%20(keyboard_keypressed))%09%0A%09(when%20(not%20(eq%20pressed_key%20nil))%0A%09%09(print%20pressed_key)%0A%09%09(print%20%22%20----%20%22%0A%09%09(print%20(keyboard_keyreleased))%0A%09%09))%0A%09%0A%09(graphics_swap)%0A%09)%0A%0A)

If you were replacing tabs with a single space (as is the workaround mentioned in #527) then it would have trimmed the indentation so that code blocks did not form.

Code blocks occur after 4 spaces (or 1 tab) of indentation and would render anything indented that far or further in a different way (this is intended behaviour).

If this isn't the issue then I'm still struggling to understand the issue unfortunately – perhaps you could post the results you are getting so that I can try to replicate them?

**Comment by exezin** [comment]
> Code blocks occur after 4 spaces (or 1 tab) of indentation and would render anything indented that far or further in a different way (this is intended behaviour).

I'm referring to manually defining code blocks, with the ```` or ~~~ etc

**Comment by aidantwoods** [comment]
Perhaps you could post the results you are getting so that I can try to replicate them, as well as any error messages if the issue is crashing Parsedown for example?

Could you also confirm that the CommonMark result is different to that given by Parsedown with the input you are struggling with? You can check the CommonMark result here: http://spec.commonmark.org/dingus/

If you put your input into http://spec.commonmark.org/dingus/ and then post the URL after clicking the  "permalink" button it would be helpful.

**Comment by aidantwoods** [comment]
Unfortunately absent of posting the problematic output here there isn't really any more I can do here because I'm unable to replicate the issue, or even really know what I'm trying to replicate. Please feel free to reopen if you can provide some more information :)
Knowing whether this occurs in the latest version would also be helpful (if you could confirm your version number?)
