### ISSUE TITLE
MathJax

### ISSUE THREAD

**Issue by imabot2** [erusev/parsedown#554]
I'm using MathJax with your wonderfull parser. I already read the issue https://github.com/erusev/parsedown/issues/369 and followed the recommandation on https://github.com/erusev/parsedown-extra/issues/81.

It works fine, here is a preview of the result : [Derivative rules](https://www.lucidar.me/en/mathematics/derivative-rules/)

My problem is that I have to escape MarkDown characters to avoid problems. I noticed that with editors like Jupyter Notebook, you don't have too.

Instead of

`$$ Q_{V_A} = 3 $$`

I have to write : 

`$$ Q\_{V\_A} = 3 $$`

I also have to escape inline markup `\\(` and `\\)` which is a bit tedious.

What is your recommandation to overcome these issues ?

**Comment by imabot2** [comment]
> But

oble

**Comment by aidantwoods** [comment]
For this specific case, I think it should work okay:
<img width="837" alt="screen shot 2018-03-27 at 13 43 09" src="https://user-images.githubusercontent.com/3288888/37967999-e3939ad6-31c4-11e8-97dd-e4f607d9035d.png">

In general the best action would be to have an extension to Parsedown prevent the parsing of things inside mathjax delimiters.
I think that this shouldn't be done in Parsedown core – since in general, markdown should work inside `$$` and other mathjax delimiters. Having it not work might be surprising for those not using mathjax.
