### ISSUE TITLE
footnotes problem

### ISSUE THREAD

**Issue by ConstantMath** [erusev/parsedown#564]
Hi, thanks for your nice work.
Since composer upgrade to the 1.7 version, the html present in footnotes is not interpreted anymore.
For exemple, paragraph are interpreted like this : `&lt;p&gt;`

It was working well in the 1.6.4 version.

**Comment by aidantwoods** [comment]
Hello!

Footnotes are part of ParsedownExtra, this particular issue is being tracked in https://github.com/erusev/parsedown-extra/issues/118 :)

**Comment by ConstantMath** [comment]
oh ok, great ;-)

**Comment by aidantwoods** [comment]
There is some progress started in #576 toward making the required information available so we can fix this properly in Parsedown extra (without having to read HTML from a string), in-case you're interested.

I'm closing this issue here since this is being tracked over in the Parsedown-extra repo, thanks for reporting this though! :)

**Comment by terrylinooo** [comment]
I develop a WordPress [Markwon editor](https://wordpress.org/plugins/wp-githuber-md/) plugin and my user reported this issue to me
https://github.com/terrylinooo/githuber-md/issues/22

After spending time to view the code, I think the only way to solve it is to modify **Parsedown.php** (line: 1507)

```
//$markup .= self::escape($Element['text'], true);
$markup .= $Element['text'];
```
