### ISSUE TITLE
Code block in html div

### ISSUE THREAD

**Issue by imabot2** [erusev/parsedown#567]
I tryed to insert a code block in a `<div>` markup :

```
<div>
` ` ` python
a = 6
` ` `
</div>
```

The code block is not parsed, I don't think it is a bug, but it is still an issue for me. Is there an option for solving this problem. 

By the way, an escape syntax for escaping a block of lines or a part of the markdown source file would really be welcome, and could probably solved many problems (like MathJax equations for example https://github.com/erusev/parsedown/issues/554).

**Comment by aidantwoods** [comment]
This will be fixed in the next release :)

One thing to note though, you'll need to put a single newline in-between `<div>` and the markdown for the code block to get the result you want, the per [CommonMark spec](http://spec.commonmark.org/0.28/#html-blocks).

You can take a look at #514 if you're interested in looking at the fix.
