### ISSUE TITLE
< br /> generation not implemented in headers

### ISSUE THREAD

**Issue by emanwebdev** [erusev/parsedown#570]
MD says: to insert a <br /> break tag using Markdown: end any line with 2 or more spaces to produce a <br /> tag.

according to [the PARAGRAPHS and LINE BREAKS syntax documentation at Daring Fireball](https://daringfireball.net/projects/markdown/syntax#p) a line that ends with two or more spaces produces a <br /> tag.

Only works inside paragraphs

Please implement inside headers as well 
and if easily possible anywhere else according to Markdown

**Comment by emanwebdev** [comment]
`<h2>LOVE ANASTASIA<br />
♥♂♀☼☺♪♫☺  </h2>`

**Comment by aidantwoods** [comment]
We do support them in *multi-line* headers as far as I can tell? :)

i.e.
<img width="647" alt="screen shot 2018-03-25 at 22 31 01" src="https://user-images.githubusercontent.com/3288888/37880161-3f0a7ea6-307c-11e8-9b10-5801c1031dee.png">

We're aiming to follow the CommonMark spec here, so headers with `#` wouldn't be candidates for this behaviour since they are necessarily one line blocks:
http://spec.commonmark.org/0.28/#hard-line-breaks
> A line break (not in a code span or HTML tag) that is preceded by two or more spaces **and does not occur at the end of a block** is parsed as a hard line break (rendered in HTML as a <br /> tag)

Do you have an input example where this isn't working as expected?
