### ISSUE TITLE
prism and mermaid conflict

### ISSUE THREAD

**Issue by oemunoz** [erusev/parsedown#629]
I was some time trying to make prism and mermaid work,

```mermaid
graph LR
	prism-- conflict ---mermaid
```
By default, parsedown adds "language" to the div class, this causes prism to process the code, and therefore mermaid does not work correctly.

At the end the workaround was to add the following code to the "blockFencedCode" function:
Parsedown.php

```php
if ($infostring !== '')
        {
                if ($infostring == 'mermaid')
                {
                    $Element['attributes'] = array('class' => $infostring);
                }
                else
                {
                    $Element['attributes'] = array('class' => "language-$infostring");
                }
        }
```

Is posible to add these lines, the advantage is that mermaid works out of the box.

**Comment by aidantwoods** [comment]
Parsedown shouldn't be adding any classes to divs? Code in the `blockFencedCode` that you've mentioned should be outputting things like:

```
<pre><code class="language-php">foo
</code></pre>
```

For this custom behaviour your best option is an implementing it in an extension (as you've essentially already done by modifying the code). Unfortunately I don't think we can really reasonably add edge cases into Parsedown for interoperability with custom software that isn't necessarily used by everyone (else we'd potentially end up with 1000s of edge cases like this).

The current behaviour matches the suggested implementation from the CommonMark spec, and while no specific treatment is mandated for the infostring by the spec, I think there should be a compelling reason to diverge. I don't really think we should set a precedent for making this kind of interoperability change, since it wouldn't be possible to accommodate for everything.

**Comment by gaffling** [comment]
I made this change to make prism work with line-numbers, is there any nicer way?

`$Element['attributes'] = array('class' => "language-$language line-numbers");`

**Comment by tovic** [comment]
[My extension](https://github.com/tovic/parsedown-extra-plugin/blob/master/README.md#code-block-class-without-language--prefix) allows more class attributes to the code block. You can even set your own language prefix [here](https://github.com/tovic/parsedown-extra-plugin/blob/7dea58d0220c8bfb7a95b4314fee5180eaaed6c2/ParsedownExtraPlugin.php#L32).
