### ISSUE TITLE
BUG: InlineURL in <a> tag creates double link

### ISSUE THREAD

**Issue by doiftrue** [erusev/parsedown#630]
How correctly fix this bug: if we have `<a>` tag with URL anchor parser works incorrectly

Lets pass test text here: http://parsedown.org/demo 

```
some text <a href="http://domen.kz/seo/">http://domen.kz/seo/</a>.
```

![](https://clip2net.com/clip/m399748/3e1e5-clip2net_180524173255-53kb.png)

**Comment by doiftrue** [comment]
I found this solution: add `(?!<\/a>)` in regular of method `inlineUrl()` .

```
/\bhttps?+:[\/]{2}[^\s<]+\b\/*+/ui
/\bhttps?+:[\/]{2}[^\s<]+\b\/*+(?!<\/a>)/ui
```

**Comment by aidantwoods** [comment]
I believe that GitHub produces a similar result? e.g. if you check the HTML output of the following:

<a href="http://domen.kz/seo/">http://domen.kz/seo/</a>

This occurs because "inline HTML" (Raw HTML in the spec) is defined to be the tag itself (but not its contents), and so the input is seen as two separate bits of raw HTML with an autolink in the middle (but not inside since the parser doesn't know that).

This to say that the spec says to parse the input
```markdown
<a href="http://domen.kz/seo/">http://domen.kz/seo/</a>
```

as the following:
```
[raw HTML][autolink][raw HTML]
```

I think while it's perhaps not ideal that the autolink is recognised in this case, there are certainly useful examples of this behaviour, e.g.:
```markdown
<a href="http://domen.kz/seo/">*hooray!*</a>
```

which parses like:
```
[raw HTML][emphasised text][raw HTML]
```

**Comment by aidantwoods** [comment]
Closing since I believe the current behaviour is in-line with the spec: https://github.github.com/gfm/#autolinks-extension-
