### ISSUE TITLE
BC break: Removal of blockFencedCodeComplete() method in 1.8.0-beta-2

### ISSUE THREAD

**Issue by dregad** [erusev/parsedown#640]
In release 1.8.0-beta-2, `blockFencedCodeComplete()` method was removed as part of PR #614 (commit d2dd736e1b41b65101098c9eeebdd7180dea24e3).

This change is actually is causing some legacy code of mine that was calling `parent::blockFencedCodeComplete()` to break with *Call to undefined method* error. 

I am not sure why the function was removed, although I'm guessing it's because it was not actually doing anything since 6bb66db00f7faf29932f96b47fc4ac60a4333e8e (https://github.com/erusev/parsedown/blob/1.8.0-beta-1/Parsedown.php#L524).

I did not actually analyze what my code was trying to do or why it was calling the parent function yet, but I just thought I'd let you know about the error; maybe you'll want to leave the function in there with just a `return $Block;` for backwards compatibility ?

**Comment by aidantwoods** [comment]
Thanks for noticing that and tracking dow the various changes :)

Yup, I recall I removed it since absence of a complete method exhibits identical behaviour to the method being the identity map ;-) I see no reason not to break the API in this case though – I apparently neglected to consider that it might be called directly.

Similarly `Parsedown::blockCodeComplete` should probably be re-added and was removed in the same PR.

**Comment by aidantwoods** [comment]
I've added the endpoints back in in #641, though as you mentioned you might want to review what your code actually does too – `blockFencedCodeComplete` would have previously taken care of some escaping (this was all centralised by moving to the renderer in 1.7) so if you replicated that escaping then you might end up with some double escaped stuff.

**Comment by dregad** [comment]
> I've added the endpoints back in in #641

Thank you !

> you might want to review what your code actually does 

I will.
