### ISSUE TITLE
Parsedown renders UTF-8 BOM as character

### ISSUE THREAD

**Issue by alystair** [erusev/parsedown#651]
1. Create MD file in UTF-8 + BOM format
2. Attempt rendering with Parsedown

Result is that rendered output starts with `&#65279;` breaking first line of file. If first line is blank, it outputs `<p>&#65279;</p>`.

**Comment by aidantwoods** [comment]
I'm not entirely sure this is a bug since Parsedown doesn't handle reading of files?

According to http://www.unicode.org/faq/utf_bom.html#bom1, a file with UTF-8 + BOM will start with the bytes `EF BB BF` (i.e. the result that you're seeing in your output). If these bytes aren't desired in the output, it would seem it is the file reader's responsibility to remove this?
