### ISSUE TITLE
Question: what does safe mode actually do?

### ISSUE THREAD

**Issue by texelate** [erusev/parsedown#652]
Thanks for Parsedown, it's great. I have been uses it in a CMS for a while but am, for the first time, using it for untrusted content. The current README says:

> Additionally Parsedown will apply sanitisation to additional scripting vectors (such as scripting link destinations) that are introduced by the markdown syntax itself.

What does “sanitisation to additional scripting vectors” actually do/mean? Is it URL encoding all links or something?

In short:

1. If you are using safe mode does that mean you never need to set `setMarkupEscaped` to `true` (though doing so won't cause any harm)?
2. If you aren't using any extensions will setting `setSafeMode` to `true` offer sufficient security?
3. If you want markup escaped is there ever a reason _not_ to use safe mode?

Thank you!

**Comment by aidantwoods** [comment]
> What does “sanitisation to additional scripting vectors” actually do/mean? Is it URL encoding all links or something?

Perhaps the best way to answer this is by looking at where `setMarkupEscaped` falls short of being safe for preventing XSS.

If input is untrusted, perhaps the easiest way to attempt to get script execution would be to input something like the following:

```html
<script>alert(1)</script>
```

with `setMarkupEscaped(true)` this will output as:
```html
&lt;script&gt;alert(1)&lt;/script&gt;
```

However, another method of attempting execution might be via use of the `javascript:` scheme, i.e.:

```html
<a href="javascript:alert(1)">click me</a>
```

with `setMarkupEscaped(true)` enabled, this will (as expected) be escaped:
```html
&lt;a href="javascript:alert(1)"&gt;click me&lt;/a&gt;
```

So this would on the surface be fine... except markdown offers a syntax for generating HTML, so we can actually achieve `<a href="javascript:alert(1)">click me</a>` without inserting it as raw HTML, specifically if we input:
```markdown
[click me](javascript:alert%281%29)
```
(where we have url encoded the parentheses so that they do not end the markdown link)

With `setMarkupEscaped(true)` this will output as:
```html
<a href="javascript:alert%281%29">click me</a>
```
which achieves script execution on the page if the user clicks the link (i.e. XSS).

It's important to note that this isn't a bug in `setMarkupEscaped(true)` (it does exactly what it is supposed to do), rather this execution is a result of what we can do with the markdown syntax (i.e. we can get around not being able to write a javascript link as HTML by writing it in markdown). This demonstrates how the markdown syntax itself can be used to introduce XSS, and so to be safe from XSS we need additional protection where the syntax is dangerous: this is what we mean by "sanitisation to additional scripting vectors [...] that are introduced by the markdown syntax".

So in short, `setSafeMode(true)` is `setMarkupEscaped(true)`, plus defence against where the markdown syntax offers scripting capabilities. What this means for links and images at the moment is that we whitelist which schemes can be used (whitelist available [here](https://github.com/erusev/parsedown/blob/c26a2ee4bf8ba0270daab7da0353f2525ca6564a/Parsedown.php#L104-L118)), and when an unknown scheme is used we "disable" it by making the colon non-literal—i.e. the link is interpreted as if it were a relative link.

> 1. If you are using safe mode does that mean you never need to set `setMarkupEscaped` to `true` (though doing so won't cause any harm)?

`setMarkupEscaped(true)` is redundant when `setSafeMode(true)` is set, but yes you could still set both without adverse effect.

> 2. If you aren't using any extensions will setting `setSafeMode` to `true` offer sufficient security?

`setSafeMode(true)` is designed to completely protect against XSS from input (if it it turns out it does not then this would be a bug). While I'm confident it works, best practice with these things is to additionally [deploy a content security policy](https://scotthelme.co.uk/content-security-policy-an-introduction/) incase the first line of defence fails, but sans any bugs it'll be sufficient on its own.

If you're using extensions they *might* take note of the safe mode setting and adjust themselves to be safe, but they also might not—it'll depend on the extensions individually.

> 3. If you want markup escaped is there ever a reason not to use safe mode?

If you didn't want the markdown syntax to permit HTML, but are operating on trusted input then you might want the ability to input scripting links yourself, or might want to link to schemes not included in Parsedown's whitelist without manually adding them to the whitelist.

**Comment by texelate** [comment]
That is one comprehensive and useful reply, thank you so much for taking the time to reply.
