### ISSUE TITLE
Can we get a list of all inline elements?

### ISSUE THREAD

**Issue by Neofox13** [erusev/parsedown#660]
I know this question sounds a bit odd but I've been reading over Parsedown.php and I still don't know what's all available with only `->line` option (for security and such it's the "limit" I'd like to use on my website.)

Thanks.

**Comment by tovic** [comment]
Try this:

``` .php
class TestParsedown extends Parsedown {
    public function __construct() {
        var_dump($this->textLevelElements);
        exit;
    }
}

new TestParsedown();
```

See line [#1965](https://github.com/erusev/parsedown/blob/c26a2ee4bf8ba0270daab7da0353f2525ca6564a/Parsedown.php#L1965)

**Comment by Neofox13** [comment]
Brilliant, thanks.

**Comment by aidantwoods** [comment]
> (for security and such it's the "limit" I'd like to use on my website.)

If you're processing untrusted user input Parsedown has [safe-mode](https://github.com/erusev/parsedown#security) to prohibit inclusion of HTML and scripting via the markdown syntax.

`line` would permit only inline element types, there's a list of them in the [CommonMark spec](https://spec.commonmark.org/0.28/#inlines), or see everything listed [here](https://github.com/erusev/parsedown/blob/92e9c27ba0e74b8b028b111d1b6f956a15c01fc1/Parsedown.php#L1017-L1030) for exactly what Parsedown permits.

Crucially the `textLevelElements` list mentioned above is only used by Parsedown so that it will make HTML elements of this type inline instead of HTML blocks—there aren't any security guarantees that this is some kind of whitelist of permitted HTML elements though, you should use safe mode if you don't want to permit arbitrary HTML being inserted.

**Comment by Neofox13** [comment]
I appreciate that! I'm using this as a learning tool for Markdown and also I'm building a website and forum by hand and have decided to use this tool for it. :) Using PHP and PDO libraries for security then Parsedown so they can do a little bit with text. :P
