### ISSUE TITLE
Nested Blocks

### ISSUE THREAD

**Issue by chrneumann** [erusev/parsedown#665]
I'm trying to implement a custom fenced markup which supports something like this:

```markdown
::: foo
Content with **markdown**
# Heading
:::
```

which should result in something like this:

```html
<div class="foo">
<p>Content with <strong>markdown</strong>
<h1>Heading</h1>
</div>
```

I'm able to parse this without support support for non-inline markdown elements like the heading. I set the handler to 'inline'. Is there a similar way to allow to let parsedown parse non-inline elements? Should be a non so uncommon case, but I could not find an implementation.

Thanks :)

**Comment by aidantwoods** [comment]
I think you mean setting the the handler to `line` (and not `inline`) :)

(Assuming you're using the latest stable) the handler is the name of the function to hand off to, and the argument given to this function is the contents of the `text` key. 

In order to achieve what you're going for you'd want the handler to be `lines` (which parses block and inline markdown elements). For a practical example see `blockQuote` which is also a container block:

https://github.com/erusev/parsedown/blob/92e9c27ba0e74b8b028b111d1b6f956a15c01fc1/Parsedown.php#L641-L655

**Comment by chrneumann** [comment]
Thanks :)
