### ISSUE TITLE
Code analyzation

### ISSUE THREAD

**Issue by kminchev** [erusev/parsedown#679]
Greetings,

recently I've come across https://github.com/squizlabs/PHP_CodeSniffer and used it against Parsedown.php. It reported **a lot** of errors and warnings. I don't know much of PHP coding and its standards to verify the errors. Someone more skilled should do that.

Hint: that tool has option to automatically fix most of the errors.

PS: if anyone heard of a similar tool, it would be nice to compare the results.

**Comment by aidantwoods** [comment]
PHP_CodeSniffer enforces *coding standards* (read: *coding conventions*, or *stylistic preferences*) so the "errors" it reports are likely due to it's default standard having opinions about things like comment styles, line length, variable capitalisation, or brace placement etc... but these aren't errors in the sense that the code is broken. Please re-open if there is a specific functional error you noticed though :)

**Comment by kminchev** [comment]
You can tell Sniffer to check against another standard than the default.
