### ISSUE TITLE
Changelog for 1.7.0?

### ISSUE THREAD

**Issue by mnapoli** [erusev/parsedown#689]
Hi, I'm trying to upgrade [Couscous](http://couscous.io/) to use 1.7.* but I don't know what changed (bc breaks?) in 1.7 since there is no changelog.

Can you shed a light on this new version?

Thanks!

**Comment by aidantwoods** [comment]
1.7.0 was a security update to address CVE-2018-1000162.

Main code included in the update: #495

If you use extensions, there *might* be breaking behaviour due to escaping being moved to a later (more centralised) place internally. If you just use Parsedown without extensions I wouldn't anticipate anything breaking.
