### ISSUE TITLE
Possible XSS injection?

### ISSUE THREAD

**Issue by gluntn** [erusev/parsedown#706]
Preface: I don't know enough about XSS injection, and I've only used the online demo. Just thought I'd share this.

I tried messing around with the script styling: 
```
Hello there
```

And by adding a `#` before the backticks, a script-tag was generated.

```
#```<script>alert("1")</script>
hello
\```
```

(minus the backslash) became
```
<h1\>```<script\>alert(1)</script></h1>
<p>hello\</p>
<pre><code></code></pre>
```

Is this the correct behaviour?

**Comment by aidantwoods** [comment]
This is expected behaviour by default (since markdown itself permits HTML), however there is [safe-mode](https://github.com/erusev/parsedown#security) if you want to accept user-input safely.
<img width="822" alt="Screenshot 2019-04-03 at 18 15 08" src="https://user-images.githubusercontent.com/3288888/55498837-73108600-563c-11e9-9075-6298b1ce58cb.png">

**Comment by gluntn** [comment]
Nice! Okay, that's good! 😁
