### ISSUE TITLE
Bracketed Links in Bullet List Get Misinterpreted as Reference-Link Definitions

### ISSUE THREAD

**Issue by neildaniels** [erusev/parsedown#712]
The following Markdown is misinterpreted. It treats the the list item `[Example]: Single` as a reference-link _definition_. Something with two or more words (like the "Other" line) are unaffected.

```
- [Example]: Single
- [Other]: Double Word

[Example]: https://www.example.com
[Other]: https://www.example.com/other
```

<img width="848" alt="Screen Shot 2019-04-18 at 10 44 34 AM" src="https://user-images.githubusercontent.com/417182/56380424-f696af00-61c6-11e9-9c68-b9cfa9d8e8c5.png">

**Comment by aidantwoods** [comment]
CommonMark does the same:

https://spec.commonmark.org/dingus/?text=-%20%5BExample%5D%3A%20Single%0A-%20%5BOther%5D%3A%20Double%20Word%0A%0A%5BExample%5D%3A%20https%3A%2F%2Fwww.example.com%0A%5BOther%5D%3A%20https%3A%2F%2Fwww.example.com%2Fother

This because list items are left blocks (they can contain other blocks).  The two word variant doesn't satisfy the syntax for a [link reference definition](https://spec.commonmark.org/0.29/#link-reference-definitions) and so ends up being rendered how you're expecting. Perhaps try using the full or [collapsed](https://spec.commonmark.org/0.29/#collapsed-reference-link) syntax for reference links so they don't look like definitions?

**Comment by neildaniels** [comment]
Thanks for the workaround.

**Comment by neildaniels** [comment]
TBH, this seems like a bug to me. Is this not going to be fixed?

**Comment by aidantwoods** [comment]
Spec bugs go in [commonmark/commonmark-spec](https://github.com/commonmark/commonmark-spec/issues/new) if you wanted to propose a way of fixing it :)
